### ISSUE TITLE
Inspect charm error

### ISSUE THREAD

**Issue by xMikux** [NCBPFluffyBear/FlowerPower#1]
## Description (Required)
when right click any charm to inspect, it will have error.

## Steps to reproduce the Issue (Required)
1. Take any attribute charm.
2. Right click, and console have error

## Expected behavior (Required)
No error when right click inspect it.

## Server Log / Error Report
https://pastebin.com/UEUe8zq0

## Environment (Required)
![image](https://user-images.githubusercontent.com/26039249/129446740-4de27c98-cd33-4cbc-a91e-2458fbde4fa7.png)

**Comment by NCBPFluffyBear** [comment]
Oops looks like I left some experimental code in there! Thanks for letting me know, will push a fix soon.

**Comment by NCBPFluffyBear** [comment]
Fixed in f71e9ef
