### ISSUE TITLE
Cannot activate the Magic Basin with the Magic wand

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FlowerPower#3]
## Description (Required)

after building the magic basin by placing 4 items frames, one on each side and right clicking with the magic wand, it stays as an experience basin, and does not become a magic basin.

## Steps to reproduce the Issue (Required)

https://youtu.be/BQxi3oa1GQM

## Expected behavior (Required)

the Magic basin to be activated

## Server Log / Error Report

no errors in console or slimefun folder

## Environment (Required)

 - Minecraft Version: 1.17.1 Paper 209
 - CS-CoreLib Version: n/a
 - Slimefun Version: 962
 - Plugin Version: 3

**Comment by NCBPFluffyBear** [comment]
The magic basin requires experience to function, you need to first deposit experience and then craft with it. Each crafting operation will consume 1 level in the basin.
