### ISSUE TITLE
Not Accepting Xp In To The Experience Tome

### ISSUE THREAD

**Issue by binula** [NCBPFluffyBear/FlowerPower#4]
Same As ''Boomer-1'' I Had 6172 levels but its saying i dont have experience

**Comment by NCBPFluffyBear** [comment]
Can you show me your server info please?

**Comment by binula** [comment]
![image](https://user-images.githubusercontent.com/76767737/132935504-94f3b54e-2a01-4a70-a16b-389e7f1ddf40.png)

**Comment by binula** [comment]
![Uploading 2021-09-11_10.18.59.png…]()

**Comment by NCBPFluffyBear** [comment]
Can you send me a video of you reproducing this and provide me with exact xp values?

**Comment by binula** [comment]
Sent from Mail for Windows From: FluffyBearSent: 10 September 2021 03:45To: NCBPFluffyBear/FlowerPowerCc: Bpkplays; AuthorSubject: Re: [NCBPFluffyBear/FlowerPower] Not Accepting Xp In To The Experience Tome (#4) Can you show me your server info please?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by binula** [comment]
https://youtu.be/avNEjhHH_G4  Sent from Mail for Windows From: FluffyBearSent: 11 September 2021 23:08To: NCBPFluffyBear/FlowerPowerCc: Bpkplays; AuthorSubject: Re: [NCBPFluffyBear/FlowerPower] Not Accepting Xp In To The Experience Tome (#4) Can you send me a video of you reproducing this and provide me with exact xp values?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by NCBPFluffyBear** [comment]
First, please stop opening and closing your tickets. It's really spammy. Second, please leave comments properly. I also asked for exact xp values, so if you could give those to me, that would be appreciated.

**Comment by binula** [comment]
Sorry about opening and closing I do it by accident instead send  Sent from Mail for Windows From: FluffyBearSent: 13 September 2021 20:19To: NCBPFluffyBear/FlowerPowerCc: Bpkplays; State changeSubject: Re: [NCBPFluffyBear/FlowerPower] Not Accepting Xp In To The Experience Tome (#4) First, please stop opening and closing your tickets. It's really spammy. Second, you didn't attach anything in your last comment.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

	
        
		Virus-free. www.avast.com

**Comment by NCBPFluffyBear** [comment]
Fixed in latest
