### ISSUE TITLE
Deposit Xp In Bulk On The Exp Tome Just Skips The Limit Till All The Xp Is Deposited 

### ISSUE THREAD

**Issue by binula** [NCBPFluffyBear/FlowerPower#5]
While Depositing Xp I Deposited 17,404 Xp Points  Than the 1,000,000 limit

**Comment by binula** [comment]
![2021-09-10_20 08 02](https://user-images.githubusercontent.com/76767737/132899667-39e08a57-8c1b-4992-b17f-256fca51fbb1.png)

**Comment by binula** [comment]
![Uploading image_2021-09-11_093503.png…]()

**Comment by binula** [comment]
![Uploading image_2021-09-11_095958.png…]()

**Comment by binula** [comment]
![2021-09-11_10 18 59](https://user-images.githubusercontent.com/76767737/132936680-2d02f5da-26c1-4efd-8b0f-e24f6006ca64.png)

**Comment by NCBPFluffyBear** [comment]
Fixed in latest
