### ISSUE TITLE
PlayerRightClickEvent to FlowerPower

### ISSUE THREAD

**Issue by SrMonsterYT** [NCBPFluffyBear/FlowerPower#6]
this keeps showing up in the console, I haven't found the real cause of this yet but I was able to save the error logs

https://mclo.gs/SjCGiB1

Paper git-Paper-130 (MC: 1.19.2)
Slimefun DEV - 1027 (git 96c873bd)
Metrics-Module #28
Java 18
Installed Addons: (17)
  Networks vDEV - 44 (git 2e7bc54c)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  ExtraTools vDEV - 36 (git 922c0324)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  DynaTech vDEV - 166 (git 92c8d415)
  HeadLimiter v23
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  Liquid vDEV - 14 (git 0f5346bf)
  Supreme vDEV - 9 (git efe13820)
  InfinityExpansion vDEV - 140 (git 0098d2fb)
  LiteXpansion vDEV - 180 (git d574b154)
  VillagerUtil vDEV - 1 (git 0a949b19)
  MobCapturer vDEV - 18 (git df36d239)
  FlowerPower vDEV - 14 (git 63a37cc0)
  SimpleStorage vDEV - 10 (git ea5e5637)
  FluffyMachines vDEV - 121 (git efca037f)

**Comment by NCBPFluffyBear** [comment]
Hi, can you try doing `/version` and send the output here? The plugin incorrectly believes you are on pre-1.17.

**Comment by NCBPFluffyBear** [comment]
Nevermind, I found the issue. Next build should have this issue fixed. Thank you for reporting!
