### ISSUE TITLE
Not working on Paper 1.20.4

### ISSUE THREAD

**Issue by nyxatledgerocks** [NCBPFluffyBear/FlowerPower#9]
FlowerPower not loading properly on 1.20.4, neither is FluffyMachines

![image](https://github.com/NCBPFluffyBear/FlowerPower/assets/134436513/424ca37f-c0b0-4084-bbc5-08994f3c9c82)

**Comment by NCBPFluffyBear** [comment]
Your slimefun is out of date. Download the latest version from https://blob.build (this goes for all addon updates)

**Comment by nyxatledgerocks** [comment]
Updated from blob.build, worked for this one but not for FluffyMachines
